window.gamesData = [
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "字句重排(有圖提示)",
        "path": "首頁 > 114公開觀課(俗語)",
        "wordwallUrl": "https://wordwall.net/play/108587/417/205",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/108587/417/205"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我會曉。(簡單排列)",
        "path": "首頁 > 114公開觀課(俗語)",
        "wordwallUrl": "https://wordwall.net/play/108277/852/335",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/108277/852/335"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語解釋配對",
        "path": "首頁 > 114公開觀課(俗語)",
        "wordwallUrl": "https://wordwall.net/play/108586/014/571",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/108586/014/571"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "真平台語｜聽聲音，揀出正確的聲母(k、kh、g、ng)",
        "path": "首頁 > 🔊聲母",
        "wordwallUrl": "https://wordwall.net/play/110898/195/903",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/110898/195/903"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "聲母k vs kh",
        "path": "首頁 > 🔊聲母",
        "wordwallUrl": "https://wordwall.net/play/109150/093/568",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/109150/093/568"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "1.寫出聲母(舌根音、齒音)",
        "path": "首頁 > 🔊聲母",
        "wordwallUrl": "https://wordwall.net/play/105332/734/960",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105332/734/960"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "1.寫出聲母(舌根音、齒音)",
        "path": "首頁 > 🔊聲母",
        "wordwallUrl": "https://wordwall.net/play/105332/717/268",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105332/717/268"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "2.選出聲母(雙脣音、舌尖音)",
        "path": "首頁 > 🔊聲母",
        "wordwallUrl": "https://wordwall.net/play/105332/585/398",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105332/585/398"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "2.寫出聲母(雙脣音、舌尖音)",
        "path": "首頁 > 🔊聲母",
        "wordwallUrl": "https://wordwall.net/play/105332/507/930",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105332/507/930"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "(綜合)聽語音找出與台羅音標對應的聲母-可切換quiz",
        "path": "首頁 > 🔊聲母",
        "wordwallUrl": "https://wordwall.net/play/105103/534/391",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105103/534/391"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "台羅拼音 雙韻母(配對)",
        "path": "首頁 > 🔊單韻母+雙韻母",
        "wordwallUrl": "https://wordwall.net/play/105148/775/978",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105148/775/978"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "三母音",
        "path": "首頁 > 🔊單韻母+雙韻母",
        "wordwallUrl": "https://wordwall.net/play/107803/678/459",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/107803/678/459"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "台羅拼音 雙韻母(鍵入答案)",
        "path": "首頁 > 🔊單韻母+雙韻母",
        "wordwallUrl": "https://wordwall.net/play/105148/679/777",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105148/679/777"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "台羅 單韻母(配對)",
        "path": "首頁 > 🔊單韻母+雙韻母",
        "wordwallUrl": "https://wordwall.net/play/105102/645/405",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105102/645/405"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "台羅 單韻母(填入韻母)",
        "path": "首頁 > 🔊單韻母+雙韻母",
        "wordwallUrl": "https://wordwall.net/play/105102/587/169",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105102/587/169"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "台羅 單韻母(聽音選字)",
        "path": "首頁 > 🔊單韻母+雙韻母",
        "wordwallUrl": "https://wordwall.net/play/95528/461/388",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95528/461/388"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "2025春台語課開學大調查",
        "path": "首頁 > 開學暖身",
        "wordwallUrl": "https://wordwall.net/play/95936/925/608",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95936/925/608"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "複製真平台語｜親情親情戇戇踅",
        "path": "首頁 > 活動闖關",
        "wordwallUrl": "https://wordwall.net/play/100833/038/139",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/100833/038/139"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "第二單元",
        "title": "複製L2-色水的詞",
        "path": "首頁 > 活動闖關",
        "wordwallUrl": "https://wordwall.net/play/95936/990/644",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95936/990/644"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "~向毒品說不(低年級)3題",
        "path": "首頁 > 活動闖關 > 反毒宣導",
        "wordwallUrl": "https://wordwall.net/play/98248/740/529",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/98248/740/529"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "向毒品說不(高年級)10題",
        "path": "首頁 > 活動闖關 > 反毒宣導",
        "wordwallUrl": "https://wordwall.net/play/99715/120/957",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/99715/120/957"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "~向毒品說不(中年級)5題",
        "path": "首頁 > 活動闖關 > 反毒宣導",
        "wordwallUrl": "https://wordwall.net/play/98248/798/618",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/98248/798/618"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "複製2-3反毒真英雄",
        "path": "首頁 > 活動闖關 > 反毒宣導",
        "wordwallUrl": "https://wordwall.net/play/98677/880/921",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/98677/880/921"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "兒童權利知多少1",
        "path": "首頁 > 活動闖關 > 兒童權利",
        "wordwallUrl": "https://wordwall.net/play/93930/719/120",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/93930/719/120"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "兒童權利知多少2",
        "path": "首頁 > 活動闖關 > 兒童權利",
        "wordwallUrl": "https://wordwall.net/play/93930/892/174",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/93930/892/174"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "班級(1~8班)",
        "path": "首頁 > 轉盤",
        "wordwallUrl": "https://wordwall.net/play/89129/855/681",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/89129/855/681"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "班級(1~9班)",
        "path": "首頁 > 轉盤",
        "wordwallUrl": "https://wordwall.net/play/89130/247/188",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/89130/247/188"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "班級號碼(一~三年級沒有30號)",
        "path": "首頁 > 轉盤",
        "wordwallUrl": "https://wordwall.net/play/89129/967/758",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/89129/967/758"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "撚盤(轉盤)",
        "path": "首頁 > 轉盤",
        "wordwallUrl": "https://wordwall.net/play/60471/454/902",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60471/454/902"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "正爿倒爿佗一爿(選出正確台語字)",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/92229/895/571",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/92229/895/571"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "TW002-台語文常用詞-B1高頻易學-台字台拼配華語-23題",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/95937/895/298",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95937/895/298"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "第二單元",
        "title": "B1L2台語火星文",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/95936/524/499",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95936/524/499"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "身體部位",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/73961/179/237",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/73961/179/237"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "顏色配對",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/73241/822/502",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/73241/822/502"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "動物配對",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/73240/685/237",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/73240/685/237"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "十二生相的台語鬥對",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/64038/876/692",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64038/876/692"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "《台灣特產佇佗位》",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/60884/233/666",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60884/233/666"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "聽看覓",
        "path": "首頁 > 主題小遊戲",
        "wordwallUrl": "https://wordwall.net/play/60638/675/477",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60638/675/477"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "第五單元",
        "title": "真平台語｜B9 L5(過年)完成課文語句",
        "path": "首頁 > 主題小遊戲 > 過年",
        "wordwallUrl": "https://wordwall.net/play/105007/534/612",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105007/534/612"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "講古--民俗活動",
        "path": "首頁 > 主題小遊戲 > 過年",
        "wordwallUrl": "https://wordwall.net/play/95936/481/734",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95936/481/734"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "康軒5-1台灣節慶美食、活動對看覓食",
        "path": "首頁 > 主題小遊戲 > 過年",
        "wordwallUrl": "https://wordwall.net/play/95937/003/186",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95937/003/186"
    },
    {
        "category": "其他主題單元",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "【真平】過年講好話",
        "path": "首頁 > 主題小遊戲 > 過年",
        "wordwallUrl": "https://wordwall.net/play/65566/987/559",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/65566/987/559"
    },
    {
        "category": "俗語遊戲",
        "grade": "五年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語解釋配對G5-1",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/107747/129/763",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/107747/129/763"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "複製俗語我來排508",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/115306/510/438",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/115306/510/438"
    },
    {
        "category": "俗語遊戲",
        "grade": "五年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排G5-1",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/107749/180/634",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/107749/180/634"
    },
    {
        "category": "俗語遊戲",
        "grade": "五年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語解釋配對G5-2",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/107747/376/258",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/107747/376/258"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "我會曉俗語(真平下學期1.2)",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/105417/886/382",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105417/886/382"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "台語俗諺應用判斷25題",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/105366/732/507",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105366/732/507"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "第二單元",
        "title": "複製第一冊第二課諺語",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/95937/069/460",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95937/069/460"
    },
    {
        "category": "俗語遊戲",
        "grade": "六年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "六下俗語配對",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/68555/980/809",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/68555/980/809"
    },
    {
        "category": "俗語遊戲",
        "grade": "六年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "【真平】G6 俗語我來排",
        "path": "首頁 > 俗語",
        "wordwallUrl": "https://wordwall.net/play/65562/938/413",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/65562/938/413"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語解釋配對508",
        "path": "首頁 > 俗語 > 508",
        "wordwallUrl": "https://wordwall.net/play/115307/551/697",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/115307/551/697"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排508",
        "path": "首頁 > 俗語 > 508",
        "wordwallUrl": "https://wordwall.net/play/115307/384/144",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/115307/384/144"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排508(音檔)",
        "path": "首頁 > 俗語 > 508",
        "wordwallUrl": "https://wordwall.net/play/115306/710/168",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/115306/710/168"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排508",
        "path": "首頁 > 俗語 > 508",
        "wordwallUrl": "https://wordwall.net/play/113926/474/900",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/113926/474/900"
    },
    {
        "category": "俗語遊戲",
        "grade": "五年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排G5-502-2",
        "path": "首頁 > 俗語 > 502",
        "wordwallUrl": "https://wordwall.net/play/115112/622/507",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/115112/622/507"
    },
    {
        "category": "俗語遊戲",
        "grade": "五年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排G5-502",
        "path": "首頁 > 俗語 > 502",
        "wordwallUrl": "https://wordwall.net/play/115112/370/429",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/115112/370/429"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排-1-10句(605)",
        "path": "首頁 > 俗語 > 605",
        "wordwallUrl": "https://wordwall.net/play/113228/214/949",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/113228/214/949"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語我來排-3 (605)",
        "path": "首頁 > 俗語 > 605",
        "wordwallUrl": "https://wordwall.net/play/113229/452/482",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/113229/452/482"
    },
    {
        "category": "俗語遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "俗語解釋配對-2 (605)",
        "path": "首頁 > 俗語 > 605",
        "wordwallUrl": "https://wordwall.net/play/113229/072/201",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/113229/072/201"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "複製真平台語｜聽聲音揀出圖片",
        "path": "首頁 > 真平台語G1",
        "wordwallUrl": "https://wordwall.net/play/111547/436/269",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/111547/436/269"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "B2果子正確的台語用字",
        "path": "首頁 > 真平台語G1",
        "wordwallUrl": "https://wordwall.net/play/60509/401/367",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60509/401/367"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "【顏色+果子】真平G1快閃記憶挑戰賽: 請記住圖片，回答問題，看你記住多少?",
        "path": "首頁 > 真平台語G1",
        "wordwallUrl": "https://wordwall.net/play/88752/758/171",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/88752/758/171"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "複製顏色配對",
        "path": "首頁 > 真平台語G1",
        "wordwallUrl": "https://wordwall.net/play/86658/148/735",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/86658/148/735"
    },
    {
        "category": "音標遊戲",
        "grade": "一年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "【真平】B1 G1動物(音標)",
        "path": "首頁 > 真平台語G1",
        "wordwallUrl": "https://wordwall.net/play/65007/988/620",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/65007/988/620"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "綜合單元",
        "title": "B1 上愛的活動",
        "path": "首頁 > 真平台語G1 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/63816/361/942",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/63816/361/942"
    },
    {
        "category": "音標遊戲",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "【真平】B9 L2 語詞、句子與拼音聽力測驗(自備耳機)",
        "path": "首頁 > 真平台語G1 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/61326/571/994",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/61326/571/994"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第四單元",
        "title": "【真平】B1 G1你上佮意啥物動物？",
        "path": "首頁 > 真平台語G1 > 上學期 > 第四課 動物",
        "wordwallUrl": "https://wordwall.net/play/65260/382/521",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/65260/382/521"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B1 L3 厝內的人 3",
        "path": "首頁 > 真平台語G1 > 上學期 > 第三課 \t心肝仔囝",
        "wordwallUrl": "https://wordwall.net/play/64243/644/619",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64243/644/619"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B1 L3 厝內的人2",
        "path": "首頁 > 真平台語G1 > 上學期 > 第三課 \t心肝仔囝",
        "wordwallUrl": "https://wordwall.net/play/64243/494/172",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64243/494/172"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B1 L3 我會曉念",
        "path": "首頁 > 真平台語G1 > 上學期 > 第三課 \t心肝仔囝",
        "wordwallUrl": "https://wordwall.net/play/63139/175/362",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/63139/175/362"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B1 L3 厝內的人",
        "path": "首頁 > 真平台語G1 > 上學期 > 第三課 \t心肝仔囝",
        "wordwallUrl": "https://wordwall.net/play/63139/109/476",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/63139/109/476"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "【真平】B1 L2文具",
        "path": "首頁 > 真平台語G1 > 上學期 > 第二課 鉛筆盒仔",
        "wordwallUrl": "https://wordwall.net/play/61384/481/318",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/61384/481/318"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B1 L1 生活情境(禮貌)",
        "path": "首頁 > 真平台語G1 > 上學期 > 第一課 拍招呼",
        "wordwallUrl": "https://wordwall.net/play/60764/498/271",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60764/498/271"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B1 L1我會曉念",
        "path": "首頁 > 真平台語G1 > 上學期 > 第一課 拍招呼",
        "wordwallUrl": "https://wordwall.net/play/60656/155/785",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60656/155/785"
    },
    {
        "category": "其他主題單元",
        "grade": "一年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B1 L1 生活用語",
        "path": "首頁 > 真平台語G1 > 上學期 > 第一課 拍招呼",
        "wordwallUrl": "https://wordwall.net/play/60639/524/783",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60639/524/783"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "不分學期",
        "unit": "第一單元",
        "title": "G2 L1 月娘變魔術",
        "path": "首頁 > 真平台語G2",
        "wordwallUrl": "https://wordwall.net/play/109149/172/156",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/109149/172/156"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "G2台語~餐具篇",
        "path": "首頁 > 真平台語G2",
        "wordwallUrl": "https://wordwall.net/play/88756/817/935",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/88756/817/935"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "不分學期",
        "unit": "第一單元",
        "title": "B4L1蔬菜",
        "path": "首頁 > 真平台語G2",
        "wordwallUrl": "https://wordwall.net/play/86658/549/304",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/86658/549/304"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B3 L3 厝內隔間：(啥物人)佇(佗位)(做啥物)",
        "path": "首頁 > 真平台語G2 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/63970/139/618",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/63970/139/618"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B3 L3 厝內的間格",
        "path": "首頁 > 真平台語G2 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/63139/867/727",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/63139/867/727"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "第四單元",
        "title": "複製真平B3L4",
        "path": "首頁 > 真平台語G2 > 上學期 > 花",
        "wordwallUrl": "https://wordwall.net/play/104272/682/248",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/104272/682/248"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "綜合單元",
        "title": "真平2年級第3册 玉蘭花 (這是啥物花)",
        "path": "首頁 > 真平台語G2 > 上學期 > 花",
        "wordwallUrl": "https://wordwall.net/play/104272/497/569",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/104272/497/569"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "【真平】B3 L2 植物",
        "path": "首頁 > 真平台語G2 > 上學期 > 花",
        "wordwallUrl": "https://wordwall.net/play/61318/651/301",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/61318/651/301"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "【真平】B3 L2 花的世界",
        "path": "首頁 > 真平台語G2 > 上學期 > 花",
        "wordwallUrl": "https://wordwall.net/play/60775/558/772",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60775/558/772"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "綜合單元",
        "title": "蟲豸thâng-thuā",
        "path": "首頁 > 真平台語G2 > 上學期 > 昆蟲",
        "wordwallUrl": "https://wordwall.net/play/95936/977/696",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95936/977/696"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B2 L1 蟲語詞講看覓",
        "path": "首頁 > 真平台語G2 > 上學期 > 昆蟲",
        "wordwallUrl": "https://wordwall.net/play/60668/581/955",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60668/581/955"
    },
    {
        "category": "其他主題單元",
        "grade": "二年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B3 L1 昆蟲的漢字",
        "path": "首頁 > 真平台語G2 > 上學期 > 昆蟲",
        "wordwallUrl": "https://wordwall.net/play/60639/264/721",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60639/264/721"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "聲母p/ph",
        "path": "首頁 > 🔊台語拼音練習",
        "wordwallUrl": "https://wordwall.net/play/99129/649/589",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/99129/649/589"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "複製台羅韻母分辨i、in、inn、ing",
        "path": "首頁 > 🔊台語拼音練習",
        "wordwallUrl": "https://wordwall.net/play/84300/926/907",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/84300/926/907"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "閩南語聲母韻母",
        "path": "首頁 > 🔊台語拼音練習",
        "wordwallUrl": "https://wordwall.net/play/62699/228/489",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/62699/228/489"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "台語用字vs台羅拼音",
        "path": "首頁 > 🔊台語拼音練習",
        "wordwallUrl": "https://wordwall.net/play/60636/228/447",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60636/228/447"
    },
    {
        "category": "音標遊戲",
        "grade": "不分年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "臺羅拼音_前測1",
        "path": "首頁 > 🔊台語拼音練習 > 沒有聲音",
        "wordwallUrl": "https://wordwall.net/play/64387/415/508",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64387/415/508"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "真平台語B6｜時間語詞分揀306",
        "path": "首頁 > 真平台語G3 > 下學期",
        "wordwallUrl": "https://wordwall.net/play/114995/392/941",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114995/392/941"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "真平台語B6｜時間語詞分看覓",
        "path": "首頁 > 真平台語G3 > 下學期",
        "wordwallUrl": "https://wordwall.net/play/114773/337/137",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114773/337/137"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "真平台語B3｜聽聲音，揀出正確的台語詞",
        "path": "首頁 > 真平台語G3 > 下學期",
        "wordwallUrl": "https://wordwall.net/play/114403/819/618",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114403/819/618"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "真平B6G3第三課306(8題)",
        "path": "首頁 > 真平台語G3 > 下學期",
        "wordwallUrl": "https://wordwall.net/play/113368/913/149",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/113368/913/149"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "真平台語｜意外傷害--圖片鬥看覓",
        "path": "首頁 > 真平台語G3 > 下學期",
        "wordwallUrl": "https://wordwall.net/play/113231/238/289",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/113231/238/289"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "真平G6B6L1L2測驗",
        "path": "首頁 > 真平台語G3 > 下學期",
        "wordwallUrl": "https://wordwall.net/play/89983/325/935",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/89983/325/935"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "【休閒場所】挑戰版~G3快閃記憶挑戰賽: 請記住圖片，回答問題，看你記住多少?",
        "path": "首頁 > 真平台語G3 > 下學期 > 三年級公開觀課",
        "wordwallUrl": "https://wordwall.net/play/89980/918/596",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/89980/918/596"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "【休閒場所】簡單版~G3快閃記憶挑戰賽: 請記住圖片，回答問題，看你記住多少?",
        "path": "首頁 > 真平台語G3 > 下學期 > 三年級公開觀課",
        "wordwallUrl": "https://wordwall.net/play/88757/214/929",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/88757/214/929"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "第二單元",
        "title": "真平G3B6L2露營(課文按組排序)",
        "path": "首頁 > 真平台語G3 > 下學期 > 三年級公開觀課",
        "wordwallUrl": "https://wordwall.net/play/89980/696/749",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/89980/696/749"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "下學期",
        "unit": "綜合單元",
        "title": "真平B6G3你上佮意做啥物？",
        "path": "首頁 > 真平台語G3 > 下學期 > 三年級公開觀課",
        "wordwallUrl": "https://wordwall.net/play/90056/714/931",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/90056/714/931"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "綜合單元",
        "title": "三上真平 下哺的點心-短詞排列",
        "path": "首頁 > 真平台語G3 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/105647/436/733",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105647/436/733"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "真平三上第二課課文-下晡的點心(課文排順序)",
        "path": "首頁 > 真平台語G3 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/95936/744/178",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95936/744/178"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "綜合單元",
        "title": "真平台語B5｜共聽著的物件揀出來(點心)",
        "path": "首頁 > 真平台語G3 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/100768/484/838",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/100768/484/838"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【T&P】B5 L1+L2 語詞&句子10題",
        "path": "首頁 > 真平台語G3 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/60765/069/246",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60765/069/246"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B5 L3 擔仔位語詞",
        "path": "首頁 > 真平台語G3 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/64038/765/103",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64038/765/103"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "三上L1L2句子複習0815",
        "path": "首頁 > 真平台語G3 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/61113/352/800",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/61113/352/800"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "三上第一課語詞講看覓(翻卡念)",
        "path": "首頁 > 真平台語G3 > 上學期 > L1上課用",
        "wordwallUrl": "https://wordwall.net/play/60655/318/223",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60655/318/223"
    },
    {
        "category": "其他主題單元",
        "grade": "三年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "三上第一課漢字vs華語配對",
        "path": "首頁 > 真平台語G3 > 上學期 > L1上課用",
        "wordwallUrl": "https://wordwall.net/play/60509/922/113",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60509/922/113"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第五單元",
        "title": "真平台語B4｜聽日期，配合正確的節日",
        "path": "首頁 > 真平台語G4 > 下學期 > L5",
        "wordwallUrl": "https://wordwall.net/play/114286/118/526",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114286/118/526"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "真平台語B4｜看圖揀出正確的動物台語詞",
        "path": "首頁 > 真平台語G4 > 下學期 > L3",
        "wordwallUrl": "https://wordwall.net/play/114285/533/799",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114285/533/799"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "B4你敢知影啥是保育類(聲音圖片)",
        "path": "首頁 > 真平台語G4 > 下學期 > L3",
        "wordwallUrl": "https://wordwall.net/play/111470/591/226",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/111470/591/226"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "B4台灣野生動物(聲音圖片)",
        "path": "首頁 > 真平台語G4 > 下學期 > L3",
        "wordwallUrl": "https://wordwall.net/play/111469/324/839",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/111469/324/839"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "真平台語B4｜完成語句",
        "path": "首頁 > 真平台語G4 > 下學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/114285/824/325",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114285/824/325"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "【真平】B8 L3測驗(16題烏白唬)",
        "path": "首頁 > 真平台語G4 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/71936/970/893",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/71936/970/893"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第二單元",
        "title": "【真平】B8 L2測驗(15題)",
        "path": "首頁 > 真平台語G4 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/70486/317/967",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/70486/317/967"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "【真平】B8 L1測驗(15題)",
        "path": "首頁 > 真平台語G4 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/108996/163/440",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/108996/163/440"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "【真平】B8G4L4.L5期末測驗(25題)",
        "path": "首頁 > 真平台語G4 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/92902/205/370",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/92902/205/370"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "【真平】B8G4L4欲按怎(15題)",
        "path": "首頁 > 真平台語G4 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/92223/919/933",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/92223/919/933"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "【真平】B8 L1測驗(14題)",
        "path": "首頁 > 真平台語G4 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/69682/798/832",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/69682/798/832"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B7 L1~L3語詞",
        "path": "首頁 > 真平台語G4 > 上學期",
        "wordwallUrl": "https://wordwall.net/play/64387/885/258",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64387/885/258"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "真平台語四上｜課文字句重組",
        "path": "首頁 > 真平台語G4 > 上學期 > L3",
        "wordwallUrl": "https://wordwall.net/play/104724/771/282",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/104724/771/282"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第四單元",
        "title": "【真平】B7 L4測驗(16題)",
        "path": "首頁 > 真平台語G4 > 上學期 > 隨堂測驗",
        "wordwallUrl": "https://wordwall.net/play/84455/076/213",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/84455/076/213"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B7 L3測驗(15題)",
        "path": "首頁 > 真平台語G4 > 上學期 > 隨堂測驗",
        "wordwallUrl": "https://wordwall.net/play/64661/130/5459",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64661/130/5459"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B7 L1測驗(12題)",
        "path": "首頁 > 真平台語G4 > 上學期 > 隨堂測驗",
        "wordwallUrl": "https://wordwall.net/play/60648/698/4151",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60648/698/4151"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "【真平】B7 L2測驗(13題)",
        "path": "首頁 > 真平台語G4 > 上學期 > 隨堂測驗",
        "wordwallUrl": "https://wordwall.net/play/62423/161/5056",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/62423/161/5056"
    },
    {
        "category": "其他主題單元",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B7 L1四上第一課-疊字詞",
        "path": "首頁 > 真平台語G4 > 上學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/60471/692/257",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60471/692/257"
    },
    {
        "category": "句型練習",
        "grade": "四年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B7 L1四上第一課做伙來造句",
        "path": "首頁 > 真平台語G4 > 上學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/60764/833/418",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60764/833/418"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第二單元",
        "title": "G5台語L4相反詞（倒反詞）",
        "path": "首頁 > 真平台語G5 > 下學期 > L2",
        "wordwallUrl": "https://wordwall.net/play/104442/279/389",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/104442/279/389"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "B10.L4｜聽聲音，共正確的台語字揀出來",
        "path": "首頁 > 真平台語G5 > 下學期 > L4",
        "wordwallUrl": "https://wordwall.net/play/114286/295/567",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114286/295/567"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "B10 G5 L4.L5 認別台灣",
        "path": "首頁 > 真平台語G5 > 下學期 > L4",
        "wordwallUrl": "https://wordwall.net/play/95936/949/923",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95936/949/923"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "真平台語B10｜請共正確的動詞揀出來",
        "path": "首頁 > 真平台語G5 > 下學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/114286/661/909",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114286/661/909"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "【真平】五下第一課(選字詞)",
        "path": "首頁 > 真平台語G5 > 下學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/69675/624/142",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/69675/624/142"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "手、跤的動作(挑戰)",
        "path": "首頁 > 真平台語G5 > 下學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/69313/984/125",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/69313/984/125"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "手、跤的動作(簡單)",
        "path": "首頁 > 真平台語G5 > 下學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/68784/512/680",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/68784/512/680"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "真平B10G5 L4L5測驗(20題)",
        "path": "首頁 > 真平台語G5 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/114770/844/1864",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/114770/844/1864"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "【真平】B10 L3 測驗502(18題)",
        "path": "首頁 > 真平台語G5 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/112772/228/217",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/112772/228/217"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第二單元",
        "title": "【真平】B10 L2 測驗(17題)",
        "path": "首頁 > 真平台語G5 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/70438/132/700",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/70438/132/700"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "【真平】B10 L1測驗(15題)",
        "path": "首頁 > 真平台語G5 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/85306/101/454",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/85306/101/454"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "【真平】B10 L4.L5測驗(25題)",
        "path": "首頁 > 真平台語G5 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/92902/233/569",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/92902/233/569"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "【真平】B10 L3 測驗(20題)",
        "path": "首頁 > 真平台語G5 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/71798/515/241",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/71798/515/241"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "【真平】B10 L4測驗(15題)",
        "path": "首頁 > 真平台語G5 > 下學期 > 平時測驗",
        "wordwallUrl": "https://wordwall.net/play/90480/494/961",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/90480/494/961"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第四單元",
        "title": "【T&P】 B11L4 ABB疊詞",
        "path": "首頁 > 真平台語G5 > 上學期 > L4",
        "wordwallUrl": "https://wordwall.net/play/105067/427/235",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/105067/427/235"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第四單元",
        "title": "【真平G5L4】2.揣出正確的倒反詞",
        "path": "首頁 > 真平台語G5 > 上學期 > L4",
        "wordwallUrl": "https://wordwall.net/play/65566/540/803",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/65566/540/803"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平G5L3】1.這家伙仔出去食礤冰，共正確的礤冰選起來。(點選喇叭聽音檔)",
        "path": "首頁 > 真平台語G5 > 上學期 > L3",
        "wordwallUrl": "https://wordwall.net/play/65566/020/976",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/65566/020/976"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B9 L3 礤冰配料2",
        "path": "首頁 > 真平台語G5 > 上學期 > L3",
        "wordwallUrl": "https://wordwall.net/play/64242/374/261",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64242/374/261"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】9-3 礤冰配料",
        "path": "首頁 > 真平台語G5 > 上學期 > L3",
        "wordwallUrl": "https://wordwall.net/play/64241/016/146",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64241/016/146"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第四單元",
        "title": "【真平】B9 L4測驗(20題)",
        "path": "首頁 > 真平台語G5 > 上學期 > TEST",
        "wordwallUrl": "https://wordwall.net/play/65563/870/830",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/65563/870/830"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B9 L3測驗(15題)",
        "path": "首頁 > 真平台語G5 > 上學期 > TEST",
        "wordwallUrl": "https://wordwall.net/play/84300/973/211",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/84300/973/211"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B9 L1.L2測驗(15題)",
        "path": "首頁 > 真平台語G5 > 上學期 > TEST",
        "wordwallUrl": "https://wordwall.net/play/84300/968/219",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/84300/968/219"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B9 L1測驗(12題)",
        "path": "首頁 > 真平台語G5 > 上學期 > TEST",
        "wordwallUrl": "https://wordwall.net/play/60774/285/3106",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60774/285/3106"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "五上第二課課文學習策略",
        "path": "首頁 > 真平台語G5 > 上學期 > L2",
        "wordwallUrl": "https://wordwall.net/play/61326/030/611",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/61326/030/611"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "五上第一課課文學習策略",
        "path": "首頁 > 真平台語G5 > 上學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/60700/107/890",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60700/107/890"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "五上第一課-共聽著的語詞添入去格仔內",
        "path": "首頁 > 真平台語G5 > 上學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/60472/310/253",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60472/310/253"
    },
    {
        "category": "其他主題單元",
        "grade": "五年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "五上第一課疊詞配對",
        "path": "首頁 > 真平台語G5 > 上學期 > L1",
        "wordwallUrl": "https://wordwall.net/play/38357/600/841",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/38357/600/841"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "下學期",
        "unit": "第三單元",
        "title": "【真平】B12 L3.L4期末測驗(25題)",
        "path": "首頁 > 真平台語G6 > 新版下學期",
        "wordwallUrl": "https://wordwall.net/play/90208/456/429",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/90208/456/429"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "下學期",
        "unit": "第二單元",
        "title": "【真平】B12 L2測驗(18題)",
        "path": "首頁 > 真平台語G6 > 新版下學期",
        "wordwallUrl": "https://wordwall.net/play/86667/659/949",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/86667/659/949"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "【真平】B12 L1測驗(20題)",
        "path": "首頁 > 真平台語G6 > 新版下學期",
        "wordwallUrl": "https://wordwall.net/play/86216/688/374",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/86216/688/374"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "【真平】G6世界特產",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/62421/497/873",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/62421/497/873"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "下學期",
        "unit": "第二單元",
        "title": "【真平】B12 L2 六下真平第二課測驗",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/70289/817/724",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/70289/817/724"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "下學期",
        "unit": "第四單元",
        "title": "【真平】B12 L4 六下真平期末測驗",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/71788/933/875",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/71788/933/875"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "下學期",
        "unit": "第一單元",
        "title": "【真平】B12 L1六下第一課測驗",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/69623/354/301",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/69623/354/301"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "不分學期",
        "unit": "第四單元",
        "title": "【真平】B11 L4 猜字(呵咾)",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/64038/809/363",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/64038/809/363"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "B11 G6 科技產品",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/63829/272/376",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/63829/272/376"
    },
    {
        "category": "音標遊戲",
        "grade": "六年級",
        "term": "不分學期",
        "unit": "綜合單元",
        "title": "【真平】G6世界各國特產—台語用字vs台羅拼音",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/62421/580/614",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/62421/580/614"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "六上第一課",
        "path": "首頁 > 真平台語G6 > 舊版真平",
        "wordwallUrl": "https://wordwall.net/play/60601/747/582",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/60601/747/582"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "不分學期",
        "unit": "第三單元",
        "title": "【真平】B11 L3 科技產品",
        "path": "首頁 > 真平台語G6 > 舊版真平 > TEST",
        "wordwallUrl": "https://wordwall.net/play/63828/987/247",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/63828/987/247"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "上學期",
        "unit": "第三單元",
        "title": "【真平】B11 L3測驗(20題)+城隍季",
        "path": "首頁 > 真平台語G6 > 新版上學期",
        "wordwallUrl": "https://wordwall.net/play/102511/045/753",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/102511/045/753"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "上學期",
        "unit": "第四單元",
        "title": "B11L4烏鴉食水-字句重排(8句)",
        "path": "首頁 > 真平台語G6 > 新版上學期",
        "wordwallUrl": "https://wordwall.net/play/104649/523/910",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/104649/523/910"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "【真平】B11 L2~L4測驗(20題)",
        "path": "首頁 > 真平台語G6 > 新版上學期",
        "wordwallUrl": "https://wordwall.net/play/100777/696/914",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/100777/696/914"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "上學期",
        "unit": "第二單元",
        "title": "【真平】B11 L2測驗(15題)",
        "path": "首頁 > 真平台語G6 > 新版上學期",
        "wordwallUrl": "https://wordwall.net/play/95525/527/205",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/95525/527/205"
    },
    {
        "category": "其他主題單元",
        "grade": "六年級",
        "term": "上學期",
        "unit": "第一單元",
        "title": "【真平】B11 L1測驗(15題)",
        "path": "首頁 > 真平台語G6 > 新版上學期",
        "wordwallUrl": "https://wordwall.net/play/62819/664/200",
        "pptEmbedUrl": "",
        "assignmentUrl": "https://wordwall.net/play/62819/664/200"
    }
];
